---
stages:
- name: MyStage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  properties:
  - name: Name
    value: Value
    type: file
  jobs:
  - name: Build
    type: builder
    build_type: npm
    script: |-
      #!/bin/bash
      npm install
- name: MyStage
  inputs:
  - type: job
    stage: MyStage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: https://api.ng.bluemix.net
      organization: milbuild@us.ibm.com
      space: dev
      application: Slack Scrum Bot
    script: |
      #!/bin/bash
      cf push "${CF_APP}"
